["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
CardCollection = [
    "src/card/CardCollection/CardCollection.cairo",
]
CardCatalog = [
    "src/card/CardCatalog/CardCatalog.cairo",
]
EnemyCollection = [
    "src/enemy/EnemyCollection/EnemyCollection.cairo",
]
EnemyCatalog = [
    "src/enemy/EnemyCatalog/EnemyCatalog.cairo",
]
SceneCollection = [
    "src/scene/SceneCollection/SceneCollection.cairo",
]
SceneCatalog = [
   "src/scene/SceneCatalog/SceneCatalog.cairo",
]
cursed_ascent = [
    "src/cursed_ascent/cursed_ascent.cairo",
]
# Scene Logic contracts
CockyImp = [
    "src/cursed_ascent/scene/cocky_imp.cairo",
]

["protostar.build"]
cairo-path = ["./lib/cairopen_contracts/src"]

["protostar.test"]
cairo-path = ["./lib/cairopen_contracts/src"]

["profile.devnet.protostar.deploy"]
gateway_url = "http://127.0.0.1:5050/"